
// <auto-generated />
// This file was generated by a R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and rebuild.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using R4Mvc;

namespace TestMvcApplication.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public HomeController()
        {
        }

        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d)
        {
        }

        [GeneratedCode("R4MVC", "1.0")]
        public const string Name = "HomeController";
        [GeneratedCode("R4MVC", "1.0")]
        public const string Area = "";
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public const string Index = "Index";
            public const string Details = "Details";
            public const string About = "About";
            public const string Contact = "Contact";
            public const string Error = "Error";
        }

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_HomeController : TestMvcApplication.Controllers.HomeController
    {
        public R4MVC_HomeController(): base (Dummy.Instance)
        {
        }

        [NonAction]
        public override Microsoft.AspNetCore.Mvc.IActionResult Index()
        {
            var callInfo = new R4MVC_Microsoft_AspNetCore_Mvc_IActionResult(Area, Name, nameof(Index));
            return callInfo;
        }
    }
}

namespace Links
{
}

namespace R4Mvc
{
    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy()
        {
        }

        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class R4MVC_Microsoft_AspNetCore_Mvc_IActionResult : IActionResult, IT4MVCCoreActionResult
{
    public R4MVC_Microsoft_AspNetCore_Mvc_IActionResult(string area, string controller, string action, string protocol = null) : base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public Task ExecuteResultAsync(ActionContext context) { return Task.FromResult(0); }

    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}

[GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static TestMvcApplication.Controllers.HomeController Home = new TestMvcApplication.Controllers.R4MVC_HomeController();
}
#pragma warning restore 1591, 3008, 3009, 0108

