
// <auto-generated />
// This file was generated by a R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and rebuild.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using R4Mvc;

namespace TestMvc5Application.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public HomeController()
        {
        }

        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d)
        {
        }

        [GeneratedCode("R4MVC", "1.0")]
        public const string Name = "HomeController";
        [GeneratedCode("R4MVC", "1.0")]
        public const string Area = "";
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public const string Index = "Index";
            public const string About = "About";
            public const string Contact = "Contact";
        }

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_HomeController : TestMvc5Application.Controllers.HomeController
    {
        public R4MVC_HomeController(): base (Dummy.Instance)
        {
        }
    }

    public partial class UserController
    {
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public UserController()
        {
        }

        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        protected UserController(Dummy d)
        {
        }

        [GeneratedCode("R4MVC", "1.0")]
        public const string Name = "UserController";
        [GeneratedCode("R4MVC", "1.0")]
        public const string Area = "";
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public const string Details = "Details";
        }

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_UserController : TestMvc5Application.Controllers.UserController
    {
        public R4MVC_UserController(): base (Dummy.Instance)
        {
        }
    }

    public partial class HomeController
    {
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public HomeController()
        {
        }

        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d)
        {
        }

        [GeneratedCode("R4MVC", "1.0")]
        public const string Name = "HomeController";
        [GeneratedCode("R4MVC", "1.0")]
        public const string Area = "";
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
        }

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_HomeController : TestMvc5Application.Controllers.HomeController
    {
        public R4MVC_HomeController(): base (Dummy.Instance)
        {
        }
    }

    public partial class T4MVC_HomeController
    {
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public T4MVC_HomeController()
        {
        }

        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        protected T4MVC_HomeController(Dummy d)
        {
        }

        [GeneratedCode("R4MVC", "1.0")]
        public const string Name = "T4MVC_HomeController";
        [GeneratedCode("R4MVC", "1.0")]
        public const string Area = "";
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public const string Index = "Index";
            public const string About = "About";
            public const string Contact = "Contact";
        }

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_T4MVC_HomeController : TestMvc5Application.Controllers.T4MVC_HomeController
    {
        public R4MVC_T4MVC_HomeController(): base (Dummy.Instance)
        {
        }
    }

    public partial class UserController
    {
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public UserController()
        {
        }

        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        protected UserController(Dummy d)
        {
        }

        [GeneratedCode("R4MVC", "1.0")]
        public const string Name = "UserController";
        [GeneratedCode("R4MVC", "1.0")]
        public const string Area = "";
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public const string Details = "Details";
        }

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_UserController : TestMvc5Application.Controllers.UserController
    {
        public R4MVC_UserController(): base (Dummy.Instance)
        {
        }
    }

    public partial class T4MVC_UserController
    {
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public T4MVC_UserController()
        {
        }

        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        protected T4MVC_UserController(Dummy d)
        {
        }

        [GeneratedCode("R4MVC", "1.0")]
        public const string Name = "T4MVC_UserController";
        [GeneratedCode("R4MVC", "1.0")]
        public const string Area = "";
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public const string Details = "Details";
        }

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public partial class R4MVC_T4MVC_UserController : TestMvc5Application.Controllers.T4MVC_UserController
    {
        public R4MVC_T4MVC_UserController(): base (Dummy.Instance)
        {
        }
    }
}

namespace Links
{
}

namespace R4Mvc
{
    [GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy()
        {
        }

        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("R4MVC", "1.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static TestMvc5Application.Controllers.HomeController Home = new TestMvc5Application.Controllers.R4MVC_HomeController();
    public static TestMvc5Application.Controllers.UserController User = new TestMvc5Application.Controllers.R4MVC_UserController();
    public static TestMvc5Application.Controllers.HomeController Home = new TestMvc5Application.Controllers.R4MVC_HomeController();
    public static TestMvc5Application.Controllers.T4MVC_HomeController T4MVC_Home = new TestMvc5Application.Controllers.R4MVC_T4MVC_HomeController();
    public static TestMvc5Application.Controllers.UserController User = new TestMvc5Application.Controllers.R4MVC_UserController();
    public static TestMvc5Application.Controllers.T4MVC_UserController T4MVC_User = new TestMvc5Application.Controllers.R4MVC_T4MVC_UserController();
}
#pragma warning restore 1591, 3008, 3009, 0108

